app = "dungeon-crawler-api"
primary_region = "lax"

[build]
dockerfile = "apps/api/Dockerfile"

[env]
PORT = "3000"

[http_service]
auto_start_machines = true
auto_stop_machines = "off"
force_https = true
internal_port = 3_000
min_machines_running = 1

  [http_service.concurrency]
  hard_limit = 1_000
  soft_limit = 800
  type = "connections"

[[vm]]
cpus = 1
memory = "256mb"
memory_mb = 256
size = "shared-cpu-1x"
